### ISSUE TITLE
HSL live data retrieval gets stuck with maximum number of running instances

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#35]
This error had been appearing occasionally, but in general not obstructing data retrieval too much. Today (March 16th) I noticed that our production server had not received any HSL live data successfully, but the `/var/log/upstart/regularroutes-scheduler.log` was full of these entries:

```
WARNING:apscheduler.scheduler:Execution of job "retrieve_hsl_data (trigger: cron[second='*/28'], next run at: 2016-03-16 16:07:28 EET)" skipped: maximum number of running instances reached (1)
WARNING:apscheduler.scheduler:Execution of job "retrieve_hsl_data (trigger: cron[second='*/28'], next run at: 2016-03-16 16:07:56 EET)" skipped: maximum number of running instances reached (1)
WARNING:apscheduler.scheduler:Execution of job "retrieve_hsl_data (trigger: cron[second='*/28'], next run at: 2016-03-16 16:08:00 EET)" skipped: maximum number of running instances reached (1)
```

At the same time the test server - theoretically with the same code - was running ok. As a first aid I stopped and re-started the service (also dropping the mass_transit_data table in between, since it wasn't up-to-date anyway), and data is currently fetched normally without any warnings.

Best to follow-up on this.

**Comment by ttolv** [comment]
Testserver was stuck like so now from Saturday, a worker thread in recvfrom -> fd/7 -> socket:[670566] -> dev.hsl.fi ESTABLISHED. The scheduler doesn't support timeouts, but urllib2 does have a timeout parameter, so added that (at 50s, so accept one maxinstances collision, try to clear up before the second one happens).

As for the intermittent collision messages, this was scheduled as scheduler.add_job(retrieve_hsl_data, "cron", second="*/28"), which turns out to mean every 00/28/56 (also evident in the log snippet there), so that 4s gap would be rather sensitive to bg load or other lag. Didn't see rationale for that choice in the commit msgs, so assuming it was intended to do something like every 28s... changed to "*/30"

Assuming fixed until proven otherwise ;) with 6871e1e
